services:

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - ./auth-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  task-db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: taskdb
    ports:
      - "5434:5432"
    volumes:
      - ./task-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  user-db:
    image: postgres:15
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5435:5432"
    volumes:
      - ./user-service/init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://auth_user:auth_pass@auth-db:5432/auth_db
      JWT_SECRET: dev-secret
      JWT_EXPIRES: 1h
      PORT: 3001
    depends_on:
      - auth-db

  task-service:
    build: ./task-service
    ports:
      - "3002:3002"
    environment:
      DATABASE_URL: postgres://admin:secret@task-db:5432/taskdb
      JWT_SECRET: dev-secret
    depends_on:
      - task-db

  user-service:
    build: ./user-service
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgres://admin:secret@user-db:5432/userdb
      JWT_SECRET: dev-secret
    depends_on:
      - user-db